name: Test Action

on:
  workflow_dispatch:


jobs:
  run-kitsu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run kitsu action
        uses: ./
        with:
          name: Souvik